### ISSUE TITLE
what are the packages doing in the first example?

### ISSUE THREAD

**Issue by AlainVagner** [b-rodrigues/rap4all#32]
Sorry, not really a R developer, this is probably a stupid question.
On [this page](https://github.com/b-rodrigues/rap4all/blob/master/project_start.qmd), could you please explain quickly what those packages are doing?

```
library(dplyr)
library(purrr)
library(readxl)
library(stringr)
library(janitor)
```

I was expecting some explanation, then it did not came ;) Or is it useful to mention loading packages here?

**Comment by b-rodrigues** [comment]
Calling `library(dplyr)` makes the functions included in `dplyr` available in the current session. I don't explain it, because as I mention in the beginning of the book I assume readers are already somewhat familiar with R.

But to be honest, the code of the example is not that important, what's important is the approach 😉

**Comment by AlainVagner** [comment]
I understand the `library` call, I was just curious to know what the `dplyr` library is doing. But yeah, I was lazy, I can search this by myself.
