### ISSUE TITLE
apt-get vs apt

### ISSUE THREAD

**Issue by AlainVagner** [b-rodrigues/rap4all#33]
On the page about git, I would recommend using `apt` instead of `apt-get`. It is not false *per se*, but why not use the more modern and potentially more user friendly version for beginner users?
More info there: https://itsfoss.com/apt-vs-apt-get-difference/
```
sudo apt update
sudo apt install git
```

**Comment by b-rodrigues** [comment]
Good point, I'll mention this but won't change now, too lazy 🤣

I've learned apt-get 15 years ago, old habits die hard!

**Comment by J-Moravec** [comment]
Adding here just because said link didn't say it out loud.

`apt` is for _interactive_ use. `apt-get` is for use in script. If/When you are trying to dockerize your solution and want to install dependencies in debian/ubuntu image, `apt` will complain if it is run in non-interactive mode (i.e., inside docker recipe).

**Comment by b-rodrigues** [comment]
Thanks @J-Moravec , didn't know that!
